### ISSUE TITLE
Why aimed to implement all pipelines at once?

### ISSUE THREAD

**Issue by maartenmennes** [Brainhack-Proceedings-2015/Earl_HBM_HCP_Nipype#2]
Could you clarify why you choose to work on all pipelines at the same time instead of fully completing a specific one?

**Comment by ericearl** [comment]
Good point.  Hopefully this newer draft answers that, "Conceptually these goals sounded reasonable enough to do all HCP scripts at once during the hackathon, but the learning and additional setup time was not accounted for, so the scope of the project was too big for two days of on and off coding, even among our eleven developers."  I may have also answered this in some of the other revisions I just made.  Please read and let me know.
