### ISSUE TITLE
Biggest road block?

### ISSUE THREAD

**Issue by maartenmennes** [Brainhack-Proceedings-2015/Earl_HBM_HCP_Nipype#3]
It would be interesting to hear about the biggest road blocks for this project. Was it the inexperience of the contributors with Nipype? Was it the complexity of the HCP minimal preprocessing pipelines? Or even the complexity of the Nipype platform?

**Comment by ericearl** [comment]
Thanks, good idea!  I revised a large part of the results section and I feel like I addressed these questions.  Let me know if you feel it needs more.
