### ISSUE TITLE
Future Goals?

### ISSUE THREAD

**Issue by maartenmennes** [Brainhack-Proceedings-2015/Earl_HBM_HCP_Nipype#4]
What are the future goals of this project? Will work continue after brainhack?

**Comment by ericearl** [comment]
I tried to address this in the new conclusions.  How does this sound?

"Future work will continue trying to achieve the original goals as stated, but may need an organizer to hold the team accountable to deadlines. To get involved with this project, please contact Eric Earl, earl@ohsu.edu."

**Comment by maartenmennes** [comment]
sounds good
