### ISSUE TITLE
Achievements?

### ISSUE THREAD

**Issue by maartenmennes** [Brainhack-Proceedings-2015/Earl_HBM_HCP_Nipype#5]
What would be the greatest achievement of this project? Getting more people acquainted and trained in Nipype? Making a first start of converting the pipelines? Hearing that the contributors now started using their new knowledge in some of their own projects?

**Comment by ericearl** [comment]
I added what I feel was the best outcome thus far.  Please let me know if you think it is incomplete or needs further explanation.

"The greatest achievement of the hackathon project was forming a collaborative team of interested Nipype developers who were trained and are ready to continue collaborating across seven institutions."

**Comment by maartenmennes** [comment]
Sounds good. I'd suggest to further add a pointer to the repository in the results section. Now you only mention that the repository is still available.

**Comment by ericearl** [comment]
Good suggestion, but I noticed the final PDF prominently features the repository URL at the top, so I am closing this issue with no further change.  Thanks again!

PDF here: https://github.com/Brainhack-Proceedings-2015/Earl_HBM_HCP_Nipype/blob/master/brainhack-report-formatted.pdf
